### ISSUE TITLE
sometimes such an error occurs

### ISSUE THREAD

**Issue by timeshift92** [qutran/swheel#3]
```
Uncaught (in promise) DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http:' cannot be created in a document with origin 'http://localhost:8089' and URL 'http://localhost:8089/table'.
    at t (webpack-internal:///../node_modules/swheel/dist/es/index.mjs:10:5810)
    at eval (webpack-internal:///../node_modules/swheel/dist/es/index.mjs:10:5284)
    at Array.eval (webpack-internal:///../node_modules/swheel/dist/es/index.mjs:10:20426)
```

**Comment by timeshift92** [comment]
I think I was wrong sorry
